param(
    [string] $Agent = 'Fake',
    [string] $WorkgroupRoot = 'docs/ai-workgroup'
)

$ErrorActionPreference = 'Stop'

function Get-UtcishTimestamp {
    return (Get-Date).ToString("yyyy-MM-ddTHHmmss")
}

function New-IsoTimestamp {
    return (Get-Date).ToString("yyyy-MM-ddTHH:mm:ssK")
}

function Read-FrontMatterValue {
    param(
        [string[]] $Lines,
        [string] $Key
    )
    foreach ($line in $Lines) {
        if ($line -match "^$([regex]::Escape($Key)):\s*(.*)$") {
            return $Matches[1].Trim().Trim('"')
        }
    }
    return ''
}

function Set-FrontMatterValue {
    param(
        [string] $FilePath,
        [string] $Key,
        [string] $Value
    )

    $lines = [System.Collections.Generic.List[string]]::new()
    foreach ($line in [System.IO.File]::ReadAllLines($FilePath, [System.Text.Encoding]::UTF8)) {
        $lines.Add($line)
    }

    if ($lines.Count -lt 2 -or $lines[0] -ne '---') {
        throw "File does not have YAML front matter: $FilePath"
    }

    $endIndex = -1
    for ($i = 1; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -eq '---') {
            $endIndex = $i
            break
        }
    }
    if ($endIndex -lt 0) {
        throw "File front matter is not closed: $FilePath"
    }

    $updated = $false
    for ($i = 1; $i -lt $endIndex; $i++) {
        if ($lines[$i] -match "^$([regex]::Escape($Key)):\s*") {
            $lines[$i] = "${Key}: $Value"
            $updated = $true
            break
        }
    }

    if (-not $updated) {
        $lines.Insert($endIndex, "${Key}: $Value")
    }

    [System.IO.File]::WriteAllLines($FilePath, $lines, [System.Text.UTF8Encoding]::new($false))
}

$inbox = Join-Path $WorkgroupRoot "inbox/$Agent"
$working = Join-Path $WorkgroupRoot "working/$Agent"
$codeXInbox = Join-Path $WorkgroupRoot 'inbox/CodeX'
$done = Join-Path $WorkgroupRoot 'done'
$eventsPath = Join-Path $WorkgroupRoot "state/events.$Agent.jsonl"

New-Item -ItemType Directory -Force -Path $working, $codeXInbox, $done, (Split-Path $eventsPath -Parent) | Out-Null

$message = Get-ChildItem -LiteralPath $inbox -Filter '*.md' -File | Sort-Object Name | Select-Object -First 1
if ($null -eq $message) {
    Write-Output "No ready messages for $Agent."
    exit 0
}

$lines = [System.IO.File]::ReadAllLines($message.FullName, [System.Text.Encoding]::UTF8)
$task = Read-FrontMatterValue -Lines $lines -Key 'task'
$messageId = Read-FrontMatterValue -Lines $lines -Key 'id'
$priority = Read-FrontMatterValue -Lines $lines -Key 'priority'
if ([string]::IsNullOrWhiteSpace($priority)) {
    $priority = 'medium'
}

$workingPath = Join-Path $working $message.Name
Move-Item -LiteralPath $message.FullName -Destination $workingPath
Set-FrontMatterValue -FilePath $workingPath -Key 'status' -Value 'claimed'
Set-FrontMatterValue -FilePath $workingPath -Key 'claimed_by' -Value "$env:COMPUTERNAME-$PID"
Set-FrontMatterValue -FilePath $workingPath -Key 'claimed_at' -Value (New-IsoTimestamp)

@{
    type = 'task_claimed'
    agent = $Agent
    message_id = $messageId
    at = (New-IsoTimestamp)
    path = $workingPath
} | ConvertTo-Json -Compress | Add-Content -LiteralPath $eventsPath -Encoding UTF8

$timestamp = Get-UtcishTimestamp
$reportName = "${timestamp}_from-$Agent`_to-CodeX_type-report_task-$task`_fake-runner-report.md"
$reportPath = Join-Path $codeXInbox $reportName
$reportId = "$task-msg-fake-report"
$createdAt = New-IsoTimestamp

$report = @"
---
id: $reportId
task: $task
from: $Agent
to: CodeX
type: report
status: reported
priority: $priority
reply_to: $messageId
requires_human: false
created_at: $createdAt
can_write: false
context_files:
  - $($workingPath -replace '\\','/')
allowed_files: []
forbidden_files:
  - .env
attempt: 0
max_attempts: 1
timeout_minutes: 30
---

# Fake Runner Report

## Summary
- Claimed `$messageId`.
- Wrote this deterministic report for Phase 0 loop validation.

## Validation
- Report generated by `fake-runner.ps1`.

## Risks
- No real AI tool was invoked.
"@

[System.IO.File]::WriteAllText($reportPath, $report, [System.Text.UTF8Encoding]::new($false))

@{
    type = 'report_written'
    agent = $Agent
    message_id = $messageId
    at = (New-IsoTimestamp)
    path = $reportPath
} | ConvertTo-Json -Compress | Add-Content -LiteralPath $eventsPath -Encoding UTF8

$donePath = Join-Path $done $message.Name
Set-FrontMatterValue -FilePath $workingPath -Key 'status' -Value 'done'
Set-FrontMatterValue -FilePath $workingPath -Key 'completed_at' -Value (New-IsoTimestamp)
Move-Item -LiteralPath $workingPath -Destination $donePath

Write-Output "Report written: $reportPath"
